<?php

return [
    'products' => [
        [
            'id' => 1,
            'name' => 'iPhone 13',
            'description' => 'iPhone 13 is designed with amazing features.',
            'price' => 1000,
            'image' => 'iphone13.png',
            'specifications' => [
                'Display' => '6.1-inch Super Retina XDR',
                'Processor' => 'A15 Bionic chip',
                'Camera' => 'Dual 12MP system',
                'Battery' => 'Up to 19 hours of video playback',
                'Storage' => '128GB, 256GB, 512GB',
            ],
        ],
        [
            'id' => 2,
            'name' => 'iPhone 14',
            'description' => 'iPhone 14 is the latest innovation.',
            'price' => 1200,
            'image' => 'iphone14.jpg',
            'specifications' => [
                'Display' => '6.1-inch Super Retina XDR',
                'Processor' => 'A16 Bionic chip',
                'Camera' => 'Dual 12MP system with Photonic Engine',
                'Battery' => 'Up to 20 hours of video playback',
                'Storage' => '128GB, 256GB, 512GB',
            ],
        ],
        [
            'id' => 3,
            'name' => 'iPhone 13 Mini',
            'description' => 'Compact and powerful.',
            'price' => 900,
            'image' => 'iphone13mini.jpeg',
            'specifications' => [
                'Display' => '5.4-inch Super Retina XDR',
                'Processor' => 'A15 Bionic chip',
                'Camera' => 'Dual 12MP system',
                'Battery' => 'Up to 17 hours of video playback',
                'Storage' => '128GB, 256GB, 512GB',
            ],
        ],
        [
            'id' => 4,
            'name' => 'iPhone 14 Pro',
            'description' => 'Professional features for everyone.',
            'price' => 1300,
            'image' => 'iphone14pro.jpeg',
            'specifications' => [
                'Display' => '6.1-inch Super Retina XDR with ProMotion',
                'Processor' => 'A16 Bionic chip',
                'Camera' => 'Triple 48MP + 12MP + 12MP system',
                'Battery' => 'Up to 23 hours of video playback',
                'Storage' => '128GB, 256GB, 512GB, 1TB',
            ],
        ],
        [
            'id' => 5,
            'name' => 'iPhone SE (2022)',
            'description' => 'Affordable with premium performance.',
            'price' => 700,
            'image' => 'iphonese2022.jpg',
            'specifications' => [
                'Display' => '4.7-inch Retina HD',
                'Processor' => 'A15 Bionic chip',
                'Camera' => 'Single 12MP system',
                'Battery' => 'Up to 15 hours of video playback',
                'Storage' => '64GB, 128GB, 256GB',
            ],
        ],
        [
            'id' => 6,
            'name' => 'iPhone 12',
            'description' => 'Classic iPhone with powerful features.',
            'price' => 850,
            'image' => 'iphone12.jpeg',
            'specifications' => [
                'Display' => '6.1-inch Super Retina XDR',
                'Processor' => 'A14 Bionic chip',
                'Camera' => 'Dual 12MP system',
                'Battery' => 'Up to 17 hours of video playback',
                'Storage' => '64GB, 128GB, 256GB',
            ],
        ],
        [
            'id' => 7,
            'name' => 'iPhone 12 Mini',
            'description' => 'Small size, big performance.',
            'price' => 750,
            'image' => 'iphone12mini.jpg',
            'specifications' => [
                'Display' => '5.4-inch Super Retina XDR',
                'Processor' => 'A14 Bionic chip',
                'Camera' => 'Dual 12MP system',
                'Battery' => 'Up to 15 hours of video playback',
                'Storage' => '64GB, 128GB, 256GB',
            ],
        ],
        [
            'id' => 8,
            'name' => 'iPhone 11',
            'description' => 'High performance at a great price.',
            'price' => 600,
            'image' => 'iphone11.jpg',
            'specifications' => [
                'Display' => '6.1-inch Liquid Retina HD',
                'Processor' => 'A13 Bionic chip',
                'Camera' => 'Dual 12MP system',
                'Battery' => 'Up to 17 hours of video playback',
                'Storage' => '64GB, 128GB, 256GB',
            ],
        ],
        [
            'id' => 9,
            'name' => 'iPhone XR',
            'description' => 'Colorful design with great performance.',
            'price' => 500,
            'image' => 'iphonexr.jpeg',
            'specifications' => [
                'Display' => '6.1-inch Liquid Retina HD',
                'Processor' => 'A12 Bionic chip',
                'Camera' => 'Single 12MP system',
                'Battery' => 'Up to 16 hours of video playback',
                'Storage' => '64GB, 128GB',
            ],
        ],
        [
            'id' => 10,
            'name' => 'iPhone XS',
            'description' => 'Premium design with advanced features.',
            'price' => 750,
            'image' => 'iphonexs.jpeg',
            'specifications' => [
                'Display' => '5.8-inch Super Retina OLED',
                'Processor' => 'A12 Bionic chip',
                'Camera' => 'Dual 12MP system',
                'Battery' => 'Up to 14 hours of video playback',
                'Storage' => '64GB, 256GB, 512GB',
            ],
        ],
    ],
];
